apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
type: Opaque
stringData:
  url: "https://discord.com/api/webhooks/1337216589178867723/8dn49HkPpSoja-EHReW2jnPocWwETeL-mULhu57V8HMOVqeL0kq6EwN1cz61sknkFZ97"
