apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-api
  labels:
    app: webhook-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-api
  template:
    metadata:
      labels:
        app: webhook-api
    spec:
      containers:
      - name: webhook-api
        image: ghcr.io/YOUR_GITHUB_USERNAME/webhook-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: discord-webhook
              key: url
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-api
spec:
  selector:
    app: webhook-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP