apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webhook-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tandrewton/devops-toolkit.git
    targetRevision: main
    path: part-a/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
