name: Build and Deploy Webhook API

on:
  push:
    branches:
      - main  # Run workflow when code is pushed to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin


    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.actor }}/webhook-api:latest part-a/webhook-app/

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ github.actor }}/webhook-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f part-a/k8s-manifests/webhook-app.yaml
        kubectl rollout restart deployment/webhook-api

